package com.telcordia.inpac.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-11-04T18:40:25.440+07:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://ws.clearinghouse.com", name = "NPCWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface NPCWebService {

    @WebMethod(action = "urn:processNPCMsg")
    @Action(input = "urn:processNPCMsg", output = "urn:processNPCMsgResponse")
    @RequestWrapper(localName = "processNPCMsg", targetNamespace = "http://ws.clearinghouse.com", className = "com.telcordia.inpac.ws.ProcessNPCMsg")
    @ResponseWrapper(localName = "processNPCMsgResponse", targetNamespace = "http://ws.clearinghouse.com", className = "com.telcordia.inpac.ws.ProcessNPCMsgResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.clearinghouse.com")
    public String processNPCMsg(
        @WebParam(name = "userId", targetNamespace = "http://ws.clearinghouse.com")
        String userId,
        @WebParam(name = "password", targetNamespace = "http://ws.clearinghouse.com")
        String password,
        @WebParam(name = "xmlMsg", targetNamespace = "http://ws.clearinghouse.com")
        String xmlMsg
    );
}
