//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2554.06.30 at 12:25:48 หลังเที่ยง ICT 
//


package com.telcordia.inpac.ws.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NPCMessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NPCMessageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="PortRequest" type="{}PortReqMsgType" maxOccurs="unbounded"/>
 *         &lt;element name="PortRequestAck" type="{}PortReqAckMsgType" maxOccurs="unbounded"/>
 *         &lt;element name="PortRequestDonor" type="{}PortReqDonorType" maxOccurs="unbounded"/>
 *         &lt;element name="PortResponse" type="{}PortRespMsgType" maxOccurs="unbounded"/>
 *         &lt;element name="PortNotification" type="{}PortNotMsgType" maxOccurs="unbounded"/>
 *         &lt;element name="PortNotificationException" type="{}PortNotExceptMsgType" maxOccurs="unbounded"/>
 *         &lt;element name="PortDeact" type="{}PortBaseMsgType" maxOccurs="unbounded"/>
 *         &lt;element name="PortDeactException" type="{}PortBaseMsgType" maxOccurs="unbounded"/>
 *         &lt;element name="PortBroadcast" type="{}PortActBroadcastMsgType" maxOccurs="unbounded"/>
 *         &lt;element name="PortBroadcastException" type="{}PortActBroadcastMsgType" maxOccurs="unbounded"/>
 *         &lt;element name="PortCancelRequest" type="{}PortCancelMsgType" maxOccurs="unbounded"/>
 *         &lt;element name="PortReversalRequestDonor" type="{}PortRvrsRequestDonorType" maxOccurs="unbounded"/>
 *         &lt;element name="PortReversalRequestRecp" type="{}PortRvrsRequestRecpType" maxOccurs="unbounded"/>
 *         &lt;element name="PortReversalBroadcast" type="{}PortActBroadcastMsgType" maxOccurs="unbounded"/>
 *         &lt;element name="NumReturnRequest" type="{}NumReturnReqMsgType" maxOccurs="unbounded"/>
 *         &lt;element name="NumReturnAck" type="{}NumReturnAckType" maxOccurs="unbounded"/>
 *         &lt;element name="NumReturnRequestDonor" type="{}NumReturnRangeHolType" maxOccurs="unbounded"/>
 *         &lt;element name="NumReturnBroadcast" type="{}NumReturnBroadcastMsgType" maxOccurs="unbounded"/>
 *         &lt;element name="SynchronisationRequest" type="{}SyncReqMsgType" maxOccurs="unbounded"/>
 *         &lt;element name="SynchronisationResponse" type="{}SyncRespMsgType" maxOccurs="unbounded"/>
 *         &lt;element name="PortTerminated" type="{}PortTerminatedMsgType" maxOccurs="unbounded"/>
 *         &lt;element name="ErrorNotification" type="{}ErrorNotifMsgType" maxOccurs="unbounded"/>
 *         &lt;element name="TimerNotification" type="{}TimerNotifMsgType" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NPCMessageType", propOrder = {
    "portRequest",
    "portRequestAck",
    "portRequestDonor",
    "portResponse",
    "portNotification",
    "portNotificationException",
    "portDeact",
    "portDeactException",
    "portBroadcast",
    "portBroadcastException",
    "portCancelRequest",
    "portReversalRequestDonor",
    "portReversalRequestRecp",
    "portReversalBroadcast",
    "numReturnRequest",
    "numReturnAck",
    "numReturnRequestDonor",
    "numReturnBroadcast",
    "synchronisationRequest",
    "synchronisationResponse",
    "portTerminated",
    "errorNotification",
    "timerNotification"
})
public class NPCMessageType {

    @XmlElement(name = "PortRequest")
    protected List<PortReqMsgType> portRequest;
    @XmlElement(name = "PortRequestAck")
    protected List<PortReqAckMsgType> portRequestAck;
    @XmlElement(name = "PortRequestDonor")
    protected List<PortReqDonorType> portRequestDonor;
    @XmlElement(name = "PortResponse")
    protected List<PortRespMsgType> portResponse;
    @XmlElement(name = "PortNotification")
    protected List<PortNotMsgType> portNotification;
    @XmlElement(name = "PortNotificationException")
    protected List<PortNotExceptMsgType> portNotificationException;
    @XmlElement(name = "PortDeact")
    protected List<PortBaseMsgType> portDeact;
    @XmlElement(name = "PortDeactException")
    protected List<PortBaseMsgType> portDeactException;
    @XmlElement(name = "PortBroadcast")
    protected List<PortActBroadcastMsgType> portBroadcast;
    @XmlElement(name = "PortBroadcastException")
    protected List<PortActBroadcastMsgType> portBroadcastException;
    @XmlElement(name = "PortCancelRequest")
    protected List<PortCancelMsgType> portCancelRequest;
    @XmlElement(name = "PortReversalRequestDonor")
    protected List<PortRvrsRequestDonorType> portReversalRequestDonor;
    @XmlElement(name = "PortReversalRequestRecp")
    protected List<PortRvrsRequestRecpType> portReversalRequestRecp;
    @XmlElement(name = "PortReversalBroadcast")
    protected List<PortActBroadcastMsgType> portReversalBroadcast;
    @XmlElement(name = "NumReturnRequest")
    protected List<NumReturnReqMsgType> numReturnRequest;
    @XmlElement(name = "NumReturnAck")
    protected List<NumReturnAckType> numReturnAck;
    @XmlElement(name = "NumReturnRequestDonor")
    protected List<NumReturnRangeHolType> numReturnRequestDonor;
    @XmlElement(name = "NumReturnBroadcast")
    protected List<NumReturnBroadcastMsgType> numReturnBroadcast;
    @XmlElement(name = "SynchronisationRequest")
    protected List<SyncReqMsgType> synchronisationRequest;
    @XmlElement(name = "SynchronisationResponse")
    protected List<SyncRespMsgType> synchronisationResponse;
    @XmlElement(name = "PortTerminated")
    protected List<PortTerminatedMsgType> portTerminated;
    @XmlElement(name = "ErrorNotification")
    protected List<ErrorNotifMsgType> errorNotification;
    @XmlElement(name = "TimerNotification")
    protected List<TimerNotifMsgType> timerNotification;

    /**
     * Gets the value of the portRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortReqMsgType }
     * 
     * 
     */
    public List<PortReqMsgType> getPortRequest() {
        if (portRequest == null) {
            portRequest = new ArrayList<PortReqMsgType>();
        }
        return this.portRequest;
    }

    /**
     * Gets the value of the portRequestAck property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portRequestAck property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortRequestAck().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortReqAckMsgType }
     * 
     * 
     */
    public List<PortReqAckMsgType> getPortRequestAck() {
        if (portRequestAck == null) {
            portRequestAck = new ArrayList<PortReqAckMsgType>();
        }
        return this.portRequestAck;
    }

    /**
     * Gets the value of the portRequestDonor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portRequestDonor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortRequestDonor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortReqDonorType }
     * 
     * 
     */
    public List<PortReqDonorType> getPortRequestDonor() {
        if (portRequestDonor == null) {
            portRequestDonor = new ArrayList<PortReqDonorType>();
        }
        return this.portRequestDonor;
    }

    /**
     * Gets the value of the portResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortRespMsgType }
     * 
     * 
     */
    public List<PortRespMsgType> getPortResponse() {
        if (portResponse == null) {
            portResponse = new ArrayList<PortRespMsgType>();
        }
        return this.portResponse;
    }

    /**
     * Gets the value of the portNotification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portNotification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortNotification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortNotMsgType }
     * 
     * 
     */
    public List<PortNotMsgType> getPortNotification() {
        if (portNotification == null) {
            portNotification = new ArrayList<PortNotMsgType>();
        }
        return this.portNotification;
    }

    /**
     * Gets the value of the portNotificationException property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portNotificationException property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortNotificationException().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortNotExceptMsgType }
     * 
     * 
     */
    public List<PortNotExceptMsgType> getPortNotificationException() {
        if (portNotificationException == null) {
            portNotificationException = new ArrayList<PortNotExceptMsgType>();
        }
        return this.portNotificationException;
    }

    /**
     * Gets the value of the portDeact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portDeact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortDeact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortBaseMsgType }
     * 
     * 
     */
    public List<PortBaseMsgType> getPortDeact() {
        if (portDeact == null) {
            portDeact = new ArrayList<PortBaseMsgType>();
        }
        return this.portDeact;
    }

    /**
     * Gets the value of the portDeactException property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portDeactException property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortDeactException().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortBaseMsgType }
     * 
     * 
     */
    public List<PortBaseMsgType> getPortDeactException() {
        if (portDeactException == null) {
            portDeactException = new ArrayList<PortBaseMsgType>();
        }
        return this.portDeactException;
    }

    /**
     * Gets the value of the portBroadcast property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portBroadcast property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortBroadcast().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortActBroadcastMsgType }
     * 
     * 
     */
    public List<PortActBroadcastMsgType> getPortBroadcast() {
        if (portBroadcast == null) {
            portBroadcast = new ArrayList<PortActBroadcastMsgType>();
        }
        return this.portBroadcast;
    }

    /**
     * Gets the value of the portBroadcastException property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portBroadcastException property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortBroadcastException().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortActBroadcastMsgType }
     * 
     * 
     */
    public List<PortActBroadcastMsgType> getPortBroadcastException() {
        if (portBroadcastException == null) {
            portBroadcastException = new ArrayList<PortActBroadcastMsgType>();
        }
        return this.portBroadcastException;
    }

    /**
     * Gets the value of the portCancelRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portCancelRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortCancelRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortCancelMsgType }
     * 
     * 
     */
    public List<PortCancelMsgType> getPortCancelRequest() {
        if (portCancelRequest == null) {
            portCancelRequest = new ArrayList<PortCancelMsgType>();
        }
        return this.portCancelRequest;
    }

    /**
     * Gets the value of the portReversalRequestDonor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portReversalRequestDonor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortReversalRequestDonor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortRvrsRequestDonorType }
     * 
     * 
     */
    public List<PortRvrsRequestDonorType> getPortReversalRequestDonor() {
        if (portReversalRequestDonor == null) {
            portReversalRequestDonor = new ArrayList<PortRvrsRequestDonorType>();
        }
        return this.portReversalRequestDonor;
    }

    /**
     * Gets the value of the portReversalRequestRecp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portReversalRequestRecp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortReversalRequestRecp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortRvrsRequestRecpType }
     * 
     * 
     */
    public List<PortRvrsRequestRecpType> getPortReversalRequestRecp() {
        if (portReversalRequestRecp == null) {
            portReversalRequestRecp = new ArrayList<PortRvrsRequestRecpType>();
        }
        return this.portReversalRequestRecp;
    }

    /**
     * Gets the value of the portReversalBroadcast property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portReversalBroadcast property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortReversalBroadcast().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortActBroadcastMsgType }
     * 
     * 
     */
    public List<PortActBroadcastMsgType> getPortReversalBroadcast() {
        if (portReversalBroadcast == null) {
            portReversalBroadcast = new ArrayList<PortActBroadcastMsgType>();
        }
        return this.portReversalBroadcast;
    }

    /**
     * Gets the value of the numReturnRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the numReturnRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNumReturnRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NumReturnReqMsgType }
     * 
     * 
     */
    public List<NumReturnReqMsgType> getNumReturnRequest() {
        if (numReturnRequest == null) {
            numReturnRequest = new ArrayList<NumReturnReqMsgType>();
        }
        return this.numReturnRequest;
    }

    /**
     * Gets the value of the numReturnAck property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the numReturnAck property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNumReturnAck().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NumReturnAckType }
     * 
     * 
     */
    public List<NumReturnAckType> getNumReturnAck() {
        if (numReturnAck == null) {
            numReturnAck = new ArrayList<NumReturnAckType>();
        }
        return this.numReturnAck;
    }

    /**
     * Gets the value of the numReturnRequestDonor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the numReturnRequestDonor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNumReturnRequestDonor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NumReturnRangeHolType }
     * 
     * 
     */
    public List<NumReturnRangeHolType> getNumReturnRequestDonor() {
        if (numReturnRequestDonor == null) {
            numReturnRequestDonor = new ArrayList<NumReturnRangeHolType>();
        }
        return this.numReturnRequestDonor;
    }

    /**
     * Gets the value of the numReturnBroadcast property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the numReturnBroadcast property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNumReturnBroadcast().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NumReturnBroadcastMsgType }
     * 
     * 
     */
    public List<NumReturnBroadcastMsgType> getNumReturnBroadcast() {
        if (numReturnBroadcast == null) {
            numReturnBroadcast = new ArrayList<NumReturnBroadcastMsgType>();
        }
        return this.numReturnBroadcast;
    }

    /**
     * Gets the value of the synchronisationRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the synchronisationRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSynchronisationRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SyncReqMsgType }
     * 
     * 
     */
    public List<SyncReqMsgType> getSynchronisationRequest() {
        if (synchronisationRequest == null) {
            synchronisationRequest = new ArrayList<SyncReqMsgType>();
        }
        return this.synchronisationRequest;
    }

    /**
     * Gets the value of the synchronisationResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the synchronisationResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSynchronisationResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SyncRespMsgType }
     * 
     * 
     */
    public List<SyncRespMsgType> getSynchronisationResponse() {
        if (synchronisationResponse == null) {
            synchronisationResponse = new ArrayList<SyncRespMsgType>();
        }
        return this.synchronisationResponse;
    }

    /**
     * Gets the value of the portTerminated property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portTerminated property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortTerminated().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortTerminatedMsgType }
     * 
     * 
     */
    public List<PortTerminatedMsgType> getPortTerminated() {
        if (portTerminated == null) {
            portTerminated = new ArrayList<PortTerminatedMsgType>();
        }
        return this.portTerminated;
    }

    /**
     * Gets the value of the errorNotification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the errorNotification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErrorNotification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorNotifMsgType }
     * 
     * 
     */
    public List<ErrorNotifMsgType> getErrorNotification() {
        if (errorNotification == null) {
            errorNotification = new ArrayList<ErrorNotifMsgType>();
        }
        return this.errorNotification;
    }

    /**
     * Gets the value of the timerNotification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timerNotification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimerNotification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimerNotifMsgType }
     * 
     * 
     */
    public List<TimerNotifMsgType> getTimerNotification() {
        if (timerNotification == null) {
            timerNotification = new ArrayList<TimerNotifMsgType>();
        }
        return this.timerNotification;
    }

    public void setErrorNotification(List<ErrorNotifMsgType> errorNotification) {
        this.errorNotification = errorNotification;
    }

    public void setNumReturnAck(List<NumReturnAckType> numReturnAck) {
        this.numReturnAck = numReturnAck;
    }

    public void setNumReturnBroadcast(List<NumReturnBroadcastMsgType> numReturnBroadcast) {
        this.numReturnBroadcast = numReturnBroadcast;
    }

    public void setNumReturnRequest(List<NumReturnReqMsgType> numReturnRequest) {
        this.numReturnRequest = numReturnRequest;
    }

    public void setNumReturnRequestDonor(List<NumReturnRangeHolType> numReturnRequestDonor) {
        this.numReturnRequestDonor = numReturnRequestDonor;
    }

    public void setPortBroadcast(List<PortActBroadcastMsgType> portBroadcast) {
        this.portBroadcast = portBroadcast;
    }

    public void setPortBroadcastException(List<PortActBroadcastMsgType> portBroadcastException) {
        this.portBroadcastException = portBroadcastException;
    }

    public void setPortCancelRequest(List<PortCancelMsgType> portCancelRequest) {
        this.portCancelRequest = portCancelRequest;
    }

    public void setPortDeact(List<PortBaseMsgType> portDeact) {
        this.portDeact = portDeact;
    }

    public void setPortDeactException(List<PortBaseMsgType> portDeactException) {
        this.portDeactException = portDeactException;
    }

    public void setPortNotification(List<PortNotMsgType> portNotification) {
        this.portNotification = portNotification;
    }

    public void setPortNotificationException(List<PortNotExceptMsgType> portNotificationException) {
        this.portNotificationException = portNotificationException;
    }

    public void setPortRequest(List<PortReqMsgType> portRequest) {
        this.portRequest = portRequest;
    }

    public void setPortRequestAck(List<PortReqAckMsgType> portRequestAck) {
        this.portRequestAck = portRequestAck;
    }

    public void setPortRequestDonor(List<PortReqDonorType> portRequestDonor) {
        this.portRequestDonor = portRequestDonor;
    }

    public void setPortResponse(List<PortRespMsgType> portResponse) {
        this.portResponse = portResponse;
    }

    public void setPortReversalBroadcast(List<PortActBroadcastMsgType> portReversalBroadcast) {
        this.portReversalBroadcast = portReversalBroadcast;
    }

    public void setPortReversalRequestDonor(List<PortRvrsRequestDonorType> portReversalRequestDonor) {
        this.portReversalRequestDonor = portReversalRequestDonor;
    }

    public void setPortReversalRequestRecp(List<PortRvrsRequestRecpType> portReversalRequestRecp) {
        this.portReversalRequestRecp = portReversalRequestRecp;
    }

    public void setPortTerminated(List<PortTerminatedMsgType> portTerminated) {
        this.portTerminated = portTerminated;
    }

    public void setSynchronisationRequest(List<SyncReqMsgType> synchronisationRequest) {
        this.synchronisationRequest = synchronisationRequest;
    }

    public void setSynchronisationResponse(List<SyncRespMsgType> synchronisationResponse) {
        this.synchronisationResponse = synchronisationResponse;
    }

    public void setTimerNotification(List<TimerNotifMsgType> timerNotification) {
        this.timerNotification = timerNotification;
    }

}
