//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2554.06.30 at 12:25:48 หลังเที่ยง ICT 
//


package com.telcordia.inpac.ws.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cat.mnp.mvno.clh.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cat.mnp.mvno.clh.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MessageHeaderType }
     * 
     */
    public MessageHeaderType createMessageHeaderType() {
        return new MessageHeaderType();
    }

    /**
     * Create an instance of {@link NumTypeWithFlagMultiRejPortDate }
     * 
     */
    public NumTypeWithFlagMultiRejPortDate createNumTypeWithFlagMultiRejPortDate() {
        return new NumTypeWithFlagMultiRejPortDate();
    }

    /**
     * Create an instance of {@link NumTypeBase }
     * 
     */
    public NumTypeBase createNumTypeBase() {
        return new NumTypeBase();
    }

    /**
     * Create an instance of {@link NPCDataType }
     * 
     */
    public NPCDataType createNPCDataType() {
        return new NPCDataType();
    }

    /**
     * Create an instance of {@link MessageFooterType }
     * 
     */
    public MessageFooterType createMessageFooterType() {
        return new MessageFooterType();
    }

    /**
     * Create an instance of {@link PortRvrsRequestRecpType }
     * 
     */
    public PortRvrsRequestRecpType createPortRvrsRequestRecpType() {
        return new PortRvrsRequestRecpType();
    }

    /**
     * Create an instance of {@link SyncReqMsgType }
     * 
     */
    public SyncReqMsgType createSyncReqMsgType() {
        return new SyncReqMsgType();
    }

    /**
     * Create an instance of {@link TimerNotifMsgType }
     * 
     */
    public TimerNotifMsgType createTimerNotifMsgType() {
        return new TimerNotifMsgType();
    }

    /**
     * Create an instance of {@link PortReqMsgType }
     * 
     */
    public PortReqMsgType createPortReqMsgType() {
        return new PortReqMsgType();
    }

    /**
     * Create an instance of {@link NumReturnBroadcastMsgType }
     * 
     */
    public NumReturnBroadcastMsgType createNumReturnBroadcastMsgType() {
        return new NumReturnBroadcastMsgType();
    }

    /**
     * Create an instance of {@link PortRespMsgType }
     * 
     */
    public PortRespMsgType createPortRespMsgType() {
        return new PortRespMsgType();
    }

    /**
     * Create an instance of {@link PortReqAckMsgType }
     * 
     */
    public PortReqAckMsgType createPortReqAckMsgType() {
        return new PortReqAckMsgType();
    }

    /**
     * Create an instance of {@link NumTypeBaseWithPaymentRef }
     * 
     */
    public NumTypeBaseWithPaymentRef createNumTypeBaseWithPaymentRef() {
        return new NumTypeBaseWithPaymentRef();
    }

    /**
     * Create an instance of {@link NumTypeWithFlagWithPaymentRef }
     * 
     */
    public NumTypeWithFlagWithPaymentRef createNumTypeWithFlagWithPaymentRef() {
        return new NumTypeWithFlagWithPaymentRef();
    }

    /**
     * Create an instance of {@link ErrorNotifMsgType }
     * 
     */
    public ErrorNotifMsgType createErrorNotifMsgType() {
        return new ErrorNotifMsgType();
    }

    /**
     * Create an instance of {@link NumReturnReqMsgType }
     * 
     */
    public NumReturnReqMsgType createNumReturnReqMsgType() {
        return new NumReturnReqMsgType();
    }

    /**
     * Create an instance of {@link PortCancelMsgType }
     * 
     */
    public PortCancelMsgType createPortCancelMsgType() {
        return new PortCancelMsgType();
    }

    /**
     * Create an instance of {@link NPCMessageData }
     * 
     */
    public NPCMessageData createNPCMessageData() {
        return new NPCMessageData();
    }

    /**
     * Create an instance of {@link PortActBroadcastMsgType }
     * 
     */
    public PortActBroadcastMsgType createPortActBroadcastMsgType() {
        return new PortActBroadcastMsgType();
    }

    /**
     * Create an instance of {@link PortRvrsRequestDonorType }
     * 
     */
    public PortRvrsRequestDonorType createPortRvrsRequestDonorType() {
        return new PortRvrsRequestDonorType();
    }

    /**
     * Create an instance of {@link PortTerminatedMsgType }
     * 
     */
    public PortTerminatedMsgType createPortTerminatedMsgType() {
        return new PortTerminatedMsgType();
    }

    /**
     * Create an instance of {@link SyncRespMsgType }
     * 
     */
    public SyncRespMsgType createSyncRespMsgType() {
        return new SyncRespMsgType();
    }

    /**
     * Create an instance of {@link NumTypeWithReject }
     * 
     */
    public NumTypeWithReject createNumTypeWithReject() {
        return new NumTypeWithReject();
    }

    /**
     * Create an instance of {@link PortNotExceptMsgType }
     * 
     */
    public PortNotExceptMsgType createPortNotExceptMsgType() {
        return new PortNotExceptMsgType();
    }

    /**
     * Create an instance of {@link NumType }
     * 
     */
    public NumType createNumType() {
        return new NumType();
    }

    /**
     * Create an instance of {@link NumTypeWithFlagMultiRej }
     * 
     */
    public NumTypeWithFlagMultiRej createNumTypeWithFlagMultiRej() {
        return new NumTypeWithFlagMultiRej();
    }

    /**
     * Create an instance of {@link PortReqDonorType }
     * 
     */
    public PortReqDonorType createPortReqDonorType() {
        return new PortReqDonorType();
    }

    /**
     * Create an instance of {@link NumTypeWithOutId }
     * 
     */
    public NumTypeWithOutId createNumTypeWithOutId() {
        return new NumTypeWithOutId();
    }

    /**
     * Create an instance of {@link NPCMessageType }
     * 
     */
    public NPCMessageType createNPCMessageType() {
        return new NPCMessageType();
    }

    /**
     * Create an instance of {@link PortBaseMsgType }
     * 
     */
    public PortBaseMsgType createPortBaseMsgType() {
        return new PortBaseMsgType();
    }

    /**
     * Create an instance of {@link SubscriberDataType }
     * 
     */
    public SubscriberDataType createSubscriberDataType() {
        return new SubscriberDataType();
    }

    /**
     * Create an instance of {@link NumReturnAckType }
     * 
     */
    public NumReturnAckType createNumReturnAckType() {
        return new NumReturnAckType();
    }

    /**
     * Create an instance of {@link PortNotMsgType }
     * 
     */
    public PortNotMsgType createPortNotMsgType() {
        return new PortNotMsgType();
    }

    /**
     * Create an instance of {@link NumReturnRangeHolType }
     * 
     */
    public NumReturnRangeHolType createNumReturnRangeHolType() {
        return new NumReturnRangeHolType();
    }

    /**
     * Create an instance of {@link NumTypeWithFlag }
     * 
     */
    public NumTypeWithFlag createNumTypeWithFlag() {
        return new NumTypeWithFlag();
    }

}
