package cat.sd.domain.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import cat.sd.domain.ObjectFactory;
import cat.sd.domain.SubScriberCoreBalanceResponse;
import cat.sd.domain.SubscriberInfoRequest;
import cat.sd.domain.SubscriberInfoResponse;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2561-05-12T23:30:56.869+07:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://domain.sd.cat/", name = "SubscriberInfoInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface SubscriberInfoInterface {

    @WebMethod
    @RequestWrapper(localName = "getInfo", targetNamespace = "http://domain.sd.cat/", className = "cat.sd.domain.GetInfo")
    @ResponseWrapper(localName = "getInfoResponse", targetNamespace = "http://domain.sd.cat/", className = "cat.sd.domain.GetInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cat.sd.domain.SubscriberInfoResponse getInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        cat.sd.domain.SubscriberInfoRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getCoreBalance", targetNamespace = "http://domain.sd.cat/", className = "cat.sd.domain.GetCoreBalance")
    @ResponseWrapper(localName = "getCoreBalanceResponse", targetNamespace = "http://domain.sd.cat/", className = "cat.sd.domain.GetCoreBalanceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public cat.sd.domain.SubScriberCoreBalanceResponse getCoreBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        cat.sd.domain.SubscriberInfoRequest arg0
    );
}
