//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.26 at 09:13:40 PM ICT 
//


package miw.xsd.soapui.config.pincode;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://eviware.com/soapui/config}settings"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}definitionCache"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}endpoints"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}operation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}resource" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="wsaVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="bindingName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="soapVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="anonymous" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="definition" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="wadlVersion" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "settings",
    "definitionCache",
    "endpoints",
    "operation",
    "resource"
})
@XmlRootElement(name = "interface")
public class Interface {

    @XmlElement(required = true)
    protected Settings settings;
    @XmlElement(required = true)
    protected DefinitionCache definitionCache;
    @XmlElement(required = true)
    protected Endpoints endpoints;
    protected List<Operation> operation;
    protected Resource resource;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "wsaVersion")
    protected String wsaVersion;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "bindingName")
    protected String bindingName;
    @XmlAttribute(name = "soapVersion")
    protected String soapVersion;
    @XmlAttribute(name = "anonymous")
    protected String anonymous;
    @XmlAttribute(name = "definition")
    protected String definition;
    @XmlAttribute(name = "wadlVersion")
    @XmlSchemaType(name = "anyURI")
    protected String wadlVersion;

    /**
     * Gets the value of the settings property.
     * 
     * @return
     *     possible object is
     *     {@link Settings }
     *     
     */
    public Settings getSettings() {
        return settings;
    }

    /**
     * Sets the value of the settings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Settings }
     *     
     */
    public void setSettings(Settings value) {
        this.settings = value;
    }

    /**
     * Gets the value of the definitionCache property.
     * 
     * @return
     *     possible object is
     *     {@link DefinitionCache }
     *     
     */
    public DefinitionCache getDefinitionCache() {
        return definitionCache;
    }

    /**
     * Sets the value of the definitionCache property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefinitionCache }
     *     
     */
    public void setDefinitionCache(DefinitionCache value) {
        this.definitionCache = value;
    }

    /**
     * Gets the value of the endpoints property.
     * 
     * @return
     *     possible object is
     *     {@link Endpoints }
     *     
     */
    public Endpoints getEndpoints() {
        return endpoints;
    }

    /**
     * Sets the value of the endpoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Endpoints }
     *     
     */
    public void setEndpoints(Endpoints value) {
        this.endpoints = value;
    }

    /**
     * Gets the value of the operation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Operation }
     * 
     * 
     */
    public List<Operation> getOperation() {
        if (operation == null) {
            operation = new ArrayList<Operation>();
        }
        return this.operation;
    }

    /**
     * Gets the value of the resource property.
     * 
     * @return
     *     possible object is
     *     {@link Resource }
     *     
     */
    public Resource getResource() {
        return resource;
    }

    /**
     * Sets the value of the resource property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resource }
     *     
     */
    public void setResource(Resource value) {
        this.resource = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the wsaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWsaVersion() {
        return wsaVersion;
    }

    /**
     * Sets the value of the wsaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWsaVersion(String value) {
        this.wsaVersion = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the bindingName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBindingName() {
        return bindingName;
    }

    /**
     * Sets the value of the bindingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBindingName(String value) {
        this.bindingName = value;
    }

    /**
     * Gets the value of the soapVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoapVersion() {
        return soapVersion;
    }

    /**
     * Sets the value of the soapVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoapVersion(String value) {
        this.soapVersion = value;
    }

    /**
     * Gets the value of the anonymous property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnonymous() {
        return anonymous;
    }

    /**
     * Sets the value of the anonymous property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnonymous(String value) {
        this.anonymous = value;
    }

    /**
     * Gets the value of the definition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefinition() {
        return definition;
    }

    /**
     * Sets the value of the definition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefinition(String value) {
        this.definition = value;
    }

    /**
     * Gets the value of the wadlVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWadlVersion() {
        return wadlVersion;
    }

    /**
     * Sets the value of the wadlVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWadlVersion(String value) {
        this.wadlVersion = value;
    }

}
