//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.26 at 09:13:40 PM ICT 
//


package miw.xsd.soapui.config.pincode;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://eviware.com/soapui/config}settings" minOccurs="0"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}endpoint" minOccurs="0"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}request" minOccurs="0"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}originalUri" minOccurs="0"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}credentials" minOccurs="0"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}jmsConfig" minOccurs="0"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}jmsPropertyConfig" minOccurs="0"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}parameters" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mediaType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="postQueryString" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "request")
public class Request {

    @XmlElementRefs({
        @XmlElementRef(name = "jmsConfig", namespace = "http://eviware.com/soapui/config", type = JmsConfig.class, required = false),
        @XmlElementRef(name = "jmsPropertyConfig", namespace = "http://eviware.com/soapui/config", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "request", namespace = "http://eviware.com/soapui/config", type = Request.class, required = false),
        @XmlElementRef(name = "credentials", namespace = "http://eviware.com/soapui/config", type = Credentials.class, required = false),
        @XmlElementRef(name = "parameters", namespace = "http://eviware.com/soapui/config", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "endpoint", namespace = "http://eviware.com/soapui/config", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "settings", namespace = "http://eviware.com/soapui/config", type = Settings.class, required = false),
        @XmlElementRef(name = "originalUri", namespace = "http://eviware.com/soapui/config", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Object> content;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "mediaType")
    protected String mediaType;
    @XmlAttribute(name = "postQueryString")
    protected String postQueryString;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JmsConfig }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Request }
     * {@link Credentials }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Settings }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link String }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the mediaType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaType() {
        return mediaType;
    }

    /**
     * Sets the value of the mediaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaType(String value) {
        this.mediaType = value;
    }

    /**
     * Gets the value of the postQueryString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostQueryString() {
        return postQueryString;
    }

    /**
     * Sets the value of the postQueryString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostQueryString(String value) {
        this.postQueryString = value;
    }

}
