//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.19 at 11:13:24 PM ICT 
//


package jaxb.clh.npcbulksync;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="MessageName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IDNumber" type="{}TranIDType"/>
 *         &lt;element name="NumberOfMessages" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="ActivatedNumbers" type="{}ActivatedNumbersType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "NPCData")
public class NPCData {

    @XmlElement(name = "MessageName", required = true, defaultValue = "Porting Data")
    protected String messageName;
    @XmlElement(name = "IDNumber", required = true)
    protected String idNumber;
    @XmlElement(name = "NumberOfMessages", required = true)
    protected BigInteger numberOfMessages;
    @XmlElement(name = "ActivatedNumbers")
    protected ActivatedNumbersType activatedNumbers;

    /**
     * Gets the value of the messageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageName() {
        return messageName;
    }

    /**
     * Sets the value of the messageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageName(String value) {
        this.messageName = value;
    }

    /**
     * Gets the value of the idNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDNumber() {
        return idNumber;
    }

    /**
     * Sets the value of the idNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDNumber(String value) {
        this.idNumber = value;
    }

    /**
     * Gets the value of the numberOfMessages property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfMessages() {
        return numberOfMessages;
    }

    /**
     * Sets the value of the numberOfMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfMessages(BigInteger value) {
        this.numberOfMessages = value;
    }

    /**
     * Gets the value of the activatedNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link ActivatedNumbersType }
     *     
     */
    public ActivatedNumbersType getActivatedNumbers() {
        return activatedNumbers;
    }

    /**
     * Sets the value of the activatedNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivatedNumbersType }
     *     
     */
    public void setActivatedNumbers(ActivatedNumbersType value) {
        this.activatedNumbers = value;
    }

}
