package mnp.pincode.wsclient;

import javax.xml.bind.JAXBElement;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.ws.client.core.WebServiceTemplate;

import cat.mnp.pincode.ws.portout.ChannelType;
import cat.mnp.pincode.ws.portout.ContactChannelType;
import cat.mnp.pincode.ws.portout.CustomerType;
import cat.mnp.pincode.ws.portout.GeneratePinCode;
import cat.mnp.pincode.ws.portout.GeneratePinCode.MsisdnList;
import cat.mnp.pincode.ws.portout.ObjectFactory;
import cat.mnp.pincode.ws.portout.PortOutResponse;

@Component
public class PortoutClient {

	private static final Logger LOGGER = LoggerFactory.getLogger(PortoutClient.class);

	@Autowired
	private WebServiceTemplate webServiceTemplate;

	public void generatePinCode() {
		ObjectFactory factory = new ObjectFactory();

		GeneratePinCode g = factory.createGeneratePinCode();
		g.setChannelType(ChannelType.WEBSITE);
		 g.setChannelRefNumber("123456789012345");
		g.setCustomerType(CustomerType.INDIVIDUAL);
		g.setCardNumber("1122233333445");
		g.setMsisdnList(new MsisdnList());
		g.getMsisdnList().getMsisdn().add("0909380000");
		g.setContactChannelType(ContactChannelType.SMS);
		g.setContactEmailAddress("a@xxx.com");
		g.setContactMsisdn("0909380001");

		JAXBElement<GeneratePinCode> gx = factory.createGeneratePinCode(g); // this is special, No @XmlRootElement generated by JAXB
		PortOutResponse pResp = (PortOutResponse) webServiceTemplate.marshalSendAndReceive(gx);
		LOGGER.info(pResp.getStatusCode()+","+pResp.getStatusDesc());

	}
}
