//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.26 at 09:00:01 PM ICT 
//


package miw.xsd.soapui.config.clh;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://eviware.com/soapui/config}settings"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}encoding"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}endpoint"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}request"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}credentials"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}jmsConfig"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}jmsPropertyConfig"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}wsaConfig"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}wsrmConfig"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "settings",
    "encoding",
    "endpoint",
    "request",
    "credentials",
    "jmsConfig",
    "jmsPropertyConfig",
    "wsaConfig",
    "wsrmConfig"
})
@XmlRootElement(name = "call")
public class Call {

    @XmlElement(required = true)
    protected Settings settings;
    @XmlElement(required = true)
    protected String encoding;
    @XmlElement(required = true)
    protected String endpoint;
    @XmlElement(required = true)
    protected Request request;
    @XmlElement(required = true)
    protected Credentials credentials;
    @XmlElement(required = true)
    protected JmsConfig jmsConfig;
    @XmlElement(required = true)
    protected String jmsPropertyConfig;
    @XmlElement(required = true)
    protected WsaConfig wsaConfig;
    @XmlElement(required = true)
    protected WsrmConfig wsrmConfig;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the settings property.
     * 
     * @return
     *     possible object is
     *     {@link Settings }
     *     
     */
    public Settings getSettings() {
        return settings;
    }

    /**
     * Sets the value of the settings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Settings }
     *     
     */
    public void setSettings(Settings value) {
        this.settings = value;
    }

    /**
     * Gets the value of the encoding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncoding() {
        return encoding;
    }

    /**
     * Sets the value of the encoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncoding(String value) {
        this.encoding = value;
    }

    /**
     * Gets the value of the endpoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndpoint() {
        return endpoint;
    }

    /**
     * Sets the value of the endpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndpoint(String value) {
        this.endpoint = value;
    }

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link Request }
     *     
     */
    public Request getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link Request }
     *     
     */
    public void setRequest(Request value) {
        this.request = value;
    }

    /**
     * Gets the value of the credentials property.
     * 
     * @return
     *     possible object is
     *     {@link Credentials }
     *     
     */
    public Credentials getCredentials() {
        return credentials;
    }

    /**
     * Sets the value of the credentials property.
     * 
     * @param value
     *     allowed object is
     *     {@link Credentials }
     *     
     */
    public void setCredentials(Credentials value) {
        this.credentials = value;
    }

    /**
     * Gets the value of the jmsConfig property.
     * 
     * @return
     *     possible object is
     *     {@link JmsConfig }
     *     
     */
    public JmsConfig getJmsConfig() {
        return jmsConfig;
    }

    /**
     * Sets the value of the jmsConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link JmsConfig }
     *     
     */
    public void setJmsConfig(JmsConfig value) {
        this.jmsConfig = value;
    }

    /**
     * Gets the value of the jmsPropertyConfig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJmsPropertyConfig() {
        return jmsPropertyConfig;
    }

    /**
     * Sets the value of the jmsPropertyConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJmsPropertyConfig(String value) {
        this.jmsPropertyConfig = value;
    }

    /**
     * Gets the value of the wsaConfig property.
     * 
     * @return
     *     possible object is
     *     {@link WsaConfig }
     *     
     */
    public WsaConfig getWsaConfig() {
        return wsaConfig;
    }

    /**
     * Sets the value of the wsaConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link WsaConfig }
     *     
     */
    public void setWsaConfig(WsaConfig value) {
        this.wsaConfig = value;
    }

    /**
     * Gets the value of the wsrmConfig property.
     * 
     * @return
     *     possible object is
     *     {@link WsrmConfig }
     *     
     */
    public WsrmConfig getWsrmConfig() {
        return wsrmConfig;
    }

    /**
     * Sets the value of the wsrmConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link WsrmConfig }
     *     
     */
    public void setWsrmConfig(WsrmConfig value) {
        this.wsrmConfig = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
