//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.26 at 09:00:01 PM ICT 
//


package miw.xsd.soapui.config.clh;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.eviware.soapui.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CancelExcessiveThreads_QNAME = new QName("http://eviware.com/soapui/config", "cancelExcessiveThreads");
    private final static QName _Properties_QNAME = new QName("http://eviware.com/soapui/config", "properties");
    private final static QName _HistoryLimit_QNAME = new QName("http://eviware.com/soapui/config", "historyLimit");
    private final static QName _StartDelay_QNAME = new QName("http://eviware.com/soapui/config", "startDelay");
    private final static QName _SelectedAuthProfile_QNAME = new QName("http://eviware.com/soapui/config", "selectedAuthProfile");
    private final static QName _AddedBasicAuthenticationTypes_QNAME = new QName("http://eviware.com/soapui/config", "addedBasicAuthenticationTypes");
    private final static QName _OAuth1ProfileContainer_QNAME = new QName("http://eviware.com/soapui/config", "oAuth1ProfileContainer");
    private final static QName _Url_QNAME = new QName("http://eviware.com/soapui/config", "url");
    private final static QName _LimitType_QNAME = new QName("http://eviware.com/soapui/config", "limitType");
    private final static QName _Encoding_QNAME = new QName("http://eviware.com/soapui/config", "encoding");
    private final static QName _ResetStatisticsOnThreadCountChange_QNAME = new QName("http://eviware.com/soapui/config", "resetStatisticsOnThreadCountChange");
    private final static QName _WssContainer_QNAME = new QName("http://eviware.com/soapui/config", "wssContainer");
    private final static QName _SensitiveInformation_QNAME = new QName("http://eviware.com/soapui/config", "sensitiveInformation");
    private final static QName _ThreadCount_QNAME = new QName("http://eviware.com/soapui/config", "threadCount");
    private final static QName _JmsPropertyConfig_QNAME = new QName("http://eviware.com/soapui/config", "jmsPropertyConfig");
    private final static QName _MaxAssertionErrors_QNAME = new QName("http://eviware.com/soapui/config", "maxAssertionErrors");
    private final static QName _Endpoint_QNAME = new QName("http://eviware.com/soapui/config", "endpoint");
    private final static QName _TestLimit_QNAME = new QName("http://eviware.com/soapui/config", "testLimit");
    private final static QName _AuthType_QNAME = new QName("http://eviware.com/soapui/config", "authType");
    private final static QName _CalculateTPSOnTimePassed_QNAME = new QName("http://eviware.com/soapui/config", "calculateTPSOnTimePassed");
    private final static QName _RunType_QNAME = new QName("http://eviware.com/soapui/config", "runType");
    private final static QName _SampleInterval_QNAME = new QName("http://eviware.com/soapui/config", "sampleInterval");
    private final static QName _Content_QNAME = new QName("http://eviware.com/soapui/config", "content");
    private final static QName _OAuth2ProfileContainer_QNAME = new QName("http://eviware.com/soapui/config", "oAuth2ProfileContainer");
    private final static QName _Type_QNAME = new QName("http://eviware.com/soapui/config", "type");
    private final static QName _StrategyInterval_QNAME = new QName("http://eviware.com/soapui/config", "strategyInterval");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.eviware.soapui.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DefinitionCache }
     * 
     */
    public DefinitionCache createDefinitionCache() {
        return new DefinitionCache();
    }

    /**
     * Create an instance of {@link Part }
     * 
     */
    public Part createPart() {
        return new Part();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link Settings }
     * 
     */
    public Settings createSettings() {
        return new Settings();
    }

    /**
     * Create an instance of {@link Setting }
     * 
     */
    public Setting createSetting() {
        return new Setting();
    }

    /**
     * Create an instance of {@link Assertion }
     * 
     */
    public Assertion createAssertion() {
        return new Assertion();
    }

    /**
     * Create an instance of {@link Credentials }
     * 
     */
    public Credentials createCredentials() {
        return new Credentials();
    }

    /**
     * Create an instance of {@link JmsConfig }
     * 
     */
    public JmsConfig createJmsConfig() {
        return new JmsConfig();
    }

    /**
     * Create an instance of {@link WsaConfig }
     * 
     */
    public WsaConfig createWsaConfig() {
        return new WsaConfig();
    }

    /**
     * Create an instance of {@link WsrmConfig }
     * 
     */
    public WsrmConfig createWsrmConfig() {
        return new WsrmConfig();
    }

    /**
     * Create an instance of {@link TestSuite }
     * 
     */
    public TestSuite createTestSuite() {
        return new TestSuite();
    }

    /**
     * Create an instance of {@link TestCase }
     * 
     */
    public TestCase createTestCase() {
        return new TestCase();
    }

    /**
     * Create an instance of {@link TestStep }
     * 
     */
    public TestStep createTestStep() {
        return new TestStep();
    }

    /**
     * Create an instance of {@link Config }
     * 
     */
    public Config createConfig() {
        return new Config();
    }

    /**
     * Create an instance of {@link Interface }
     * 
     */
    public Interface createInterface() {
        return new Interface();
    }

    /**
     * Create an instance of {@link Endpoints }
     * 
     */
    public Endpoints createEndpoints() {
        return new Endpoints();
    }

    /**
     * Create an instance of {@link Operation }
     * 
     */
    public Operation createOperation() {
        return new Operation();
    }

    /**
     * Create an instance of {@link Call }
     * 
     */
    public Call createCall() {
        return new Call();
    }

    /**
     * Create an instance of {@link LoadTest }
     * 
     */
    public LoadTest createLoadTest() {
        return new LoadTest();
    }

    /**
     * Create an instance of {@link LoadStrategy }
     * 
     */
    public LoadStrategy createLoadStrategy() {
        return new LoadStrategy();
    }

    /**
     * Create an instance of {@link SoapuiProject }
     * 
     */
    public SoapuiProject createSoapuiProject() {
        return new SoapuiProject();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "cancelExcessiveThreads")
    public JAXBElement<String> createCancelExcessiveThreads(String value) {
        return new JAXBElement<String>(_CancelExcessiveThreads_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "properties")
    public JAXBElement<String> createProperties(String value) {
        return new JAXBElement<String>(_Properties_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "historyLimit")
    public JAXBElement<Byte> createHistoryLimit(Byte value) {
        return new JAXBElement<Byte>(_HistoryLimit_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "startDelay")
    public JAXBElement<Byte> createStartDelay(Byte value) {
        return new JAXBElement<Byte>(_StartDelay_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "selectedAuthProfile")
    public JAXBElement<String> createSelectedAuthProfile(String value) {
        return new JAXBElement<String>(_SelectedAuthProfile_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "addedBasicAuthenticationTypes")
    public JAXBElement<String> createAddedBasicAuthenticationTypes(String value) {
        return new JAXBElement<String>(_AddedBasicAuthenticationTypes_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "oAuth1ProfileContainer")
    public JAXBElement<String> createOAuth1ProfileContainer(String value) {
        return new JAXBElement<String>(_OAuth1ProfileContainer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "url")
    public JAXBElement<String> createUrl(String value) {
        return new JAXBElement<String>(_Url_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "limitType")
    public JAXBElement<String> createLimitType(String value) {
        return new JAXBElement<String>(_LimitType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "encoding")
    public JAXBElement<String> createEncoding(String value) {
        return new JAXBElement<String>(_Encoding_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "resetStatisticsOnThreadCountChange")
    public JAXBElement<String> createResetStatisticsOnThreadCountChange(String value) {
        return new JAXBElement<String>(_ResetStatisticsOnThreadCountChange_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "wssContainer")
    public JAXBElement<String> createWssContainer(String value) {
        return new JAXBElement<String>(_WssContainer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "sensitiveInformation")
    public JAXBElement<String> createSensitiveInformation(String value) {
        return new JAXBElement<String>(_SensitiveInformation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "threadCount")
    public JAXBElement<Byte> createThreadCount(Byte value) {
        return new JAXBElement<Byte>(_ThreadCount_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "jmsPropertyConfig")
    public JAXBElement<String> createJmsPropertyConfig(String value) {
        return new JAXBElement<String>(_JmsPropertyConfig_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "maxAssertionErrors")
    public JAXBElement<Byte> createMaxAssertionErrors(Byte value) {
        return new JAXBElement<Byte>(_MaxAssertionErrors_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "endpoint")
    public JAXBElement<String> createEndpoint(String value) {
        return new JAXBElement<String>(_Endpoint_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "testLimit")
    public JAXBElement<Byte> createTestLimit(Byte value) {
        return new JAXBElement<Byte>(_TestLimit_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "authType")
    public JAXBElement<String> createAuthType(String value) {
        return new JAXBElement<String>(_AuthType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "calculateTPSOnTimePassed")
    public JAXBElement<String> createCalculateTPSOnTimePassed(String value) {
        return new JAXBElement<String>(_CalculateTPSOnTimePassed_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "runType")
    public JAXBElement<String> createRunType(String value) {
        return new JAXBElement<String>(_RunType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "sampleInterval")
    public JAXBElement<Short> createSampleInterval(Short value) {
        return new JAXBElement<Short>(_SampleInterval_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "content")
    public JAXBElement<String> createContent(String value) {
        return new JAXBElement<String>(_Content_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "oAuth2ProfileContainer")
    public JAXBElement<String> createOAuth2ProfileContainer(String value) {
        return new JAXBElement<String>(_OAuth2ProfileContainer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eviware.com/soapui/config", name = "strategyInterval")
    public JAXBElement<Short> createStrategyInterval(Short value) {
        return new JAXBElement<Short>(_StrategyInterval_QNAME, Short.class, null, value);
    }

}
