//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.26 at 09:00:01 PM ICT 
//


package miw.xsd.soapui.config.clh;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://eviware.com/soapui/config}settings"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}interface"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}testSuite"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}properties"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}wssContainer"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}oAuth2ProfileContainer"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}oAuth1ProfileContainer"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}sensitiveInformation"/>
 *       &lt;/choice>
 *       &lt;attribute name="activeEnvironment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="resourceRoot" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="soapui-version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="abortOnError" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="runType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "settingsOrInterfaceOrTestSuite"
})
@XmlRootElement(name = "soapui-project")
public class SoapuiProject {

    @XmlElementRefs({
        @XmlElementRef(name = "properties", namespace = "http://eviware.com/soapui/config", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "oAuth2ProfileContainer", namespace = "http://eviware.com/soapui/config", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "oAuth1ProfileContainer", namespace = "http://eviware.com/soapui/config", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "wssContainer", namespace = "http://eviware.com/soapui/config", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "interface", namespace = "http://eviware.com/soapui/config", type = Interface.class, required = false),
        @XmlElementRef(name = "settings", namespace = "http://eviware.com/soapui/config", type = Settings.class, required = false),
        @XmlElementRef(name = "testSuite", namespace = "http://eviware.com/soapui/config", type = TestSuite.class, required = false),
        @XmlElementRef(name = "sensitiveInformation", namespace = "http://eviware.com/soapui/config", type = JAXBElement.class, required = false)
    })
    protected List<Object> settingsOrInterfaceOrTestSuite;
    @XmlAttribute(name = "activeEnvironment")
    protected String activeEnvironment;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "resourceRoot")
    protected String resourceRoot;
    @XmlAttribute(name = "soapui-version")
    protected String soapuiVersion;
    @XmlAttribute(name = "abortOnError")
    protected String abortOnError;
    @XmlAttribute(name = "runType")
    protected String runType;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the settingsOrInterfaceOrTestSuite property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the settingsOrInterfaceOrTestSuite property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSettingsOrInterfaceOrTestSuite().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Interface }
     * {@link Settings }
     * {@link TestSuite }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getSettingsOrInterfaceOrTestSuite() {
        if (settingsOrInterfaceOrTestSuite == null) {
            settingsOrInterfaceOrTestSuite = new ArrayList<Object>();
        }
        return this.settingsOrInterfaceOrTestSuite;
    }

    /**
     * Gets the value of the activeEnvironment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveEnvironment() {
        return activeEnvironment;
    }

    /**
     * Sets the value of the activeEnvironment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveEnvironment(String value) {
        this.activeEnvironment = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the resourceRoot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceRoot() {
        return resourceRoot;
    }

    /**
     * Sets the value of the resourceRoot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceRoot(String value) {
        this.resourceRoot = value;
    }

    /**
     * Gets the value of the soapuiVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoapuiVersion() {
        return soapuiVersion;
    }

    /**
     * Sets the value of the soapuiVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoapuiVersion(String value) {
        this.soapuiVersion = value;
    }

    /**
     * Gets the value of the abortOnError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbortOnError() {
        return abortOnError;
    }

    /**
     * Sets the value of the abortOnError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbortOnError(String value) {
        this.abortOnError = value;
    }

    /**
     * Gets the value of the runType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunType() {
        return runType;
    }

    /**
     * Sets the value of the runType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunType(String value) {
        this.runType = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
