//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.26 at 09:00:01 PM ICT 
//


package miw.xsd.soapui.config.clh;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://eviware.com/soapui/config}settings"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}testStep"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}loadTest"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}properties"/>
 *       &lt;/sequence>
 *       &lt;attribute name="failOnError" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="failTestCaseOnErrors" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="keepSession" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="maxResults" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="searchProperties" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "settings",
    "testStep",
    "loadTest",
    "properties"
})
@XmlRootElement(name = "testCase")
public class TestCase {

    @XmlElement(required = true)
    protected Settings settings;
    @XmlElement(required = true)
    protected TestStep testStep;
    @XmlElement(required = true)
    protected LoadTest loadTest;
    @XmlElement(required = true)
    protected String properties;
    @XmlAttribute(name = "failOnError")
    protected String failOnError;
    @XmlAttribute(name = "failTestCaseOnErrors")
    protected String failTestCaseOnErrors;
    @XmlAttribute(name = "keepSession")
    protected String keepSession;
    @XmlAttribute(name = "maxResults")
    protected Byte maxResults;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "searchProperties")
    protected String searchProperties;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the settings property.
     * 
     * @return
     *     possible object is
     *     {@link Settings }
     *     
     */
    public Settings getSettings() {
        return settings;
    }

    /**
     * Sets the value of the settings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Settings }
     *     
     */
    public void setSettings(Settings value) {
        this.settings = value;
    }

    /**
     * Gets the value of the testStep property.
     * 
     * @return
     *     possible object is
     *     {@link TestStep }
     *     
     */
    public TestStep getTestStep() {
        return testStep;
    }

    /**
     * Sets the value of the testStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestStep }
     *     
     */
    public void setTestStep(TestStep value) {
        this.testStep = value;
    }

    /**
     * Gets the value of the loadTest property.
     * 
     * @return
     *     possible object is
     *     {@link LoadTest }
     *     
     */
    public LoadTest getLoadTest() {
        return loadTest;
    }

    /**
     * Sets the value of the loadTest property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadTest }
     *     
     */
    public void setLoadTest(LoadTest value) {
        this.loadTest = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProperties(String value) {
        this.properties = value;
    }

    /**
     * Gets the value of the failOnError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFailOnError() {
        return failOnError;
    }

    /**
     * Sets the value of the failOnError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFailOnError(String value) {
        this.failOnError = value;
    }

    /**
     * Gets the value of the failTestCaseOnErrors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFailTestCaseOnErrors() {
        return failTestCaseOnErrors;
    }

    /**
     * Sets the value of the failTestCaseOnErrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFailTestCaseOnErrors(String value) {
        this.failTestCaseOnErrors = value;
    }

    /**
     * Gets the value of the keepSession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeepSession() {
        return keepSession;
    }

    /**
     * Sets the value of the keepSession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeepSession(String value) {
        this.keepSession = value;
    }

    /**
     * Gets the value of the maxResults property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getMaxResults() {
        return maxResults;
    }

    /**
     * Sets the value of the maxResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setMaxResults(Byte value) {
        this.maxResults = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the searchProperties property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchProperties() {
        return searchProperties;
    }

    /**
     * Sets the value of the searchProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchProperties(String value) {
        this.searchProperties = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
