
package org.rtcproject.ws.mnp;


import org.rtcproject.ws.jaxb.*;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RTC_WSPortType", targetNamespace = "http://rtcproject.org/MNP_WS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RTCWSPortType {


    /**
     * 
     * @param rtcPORTIN
     * @return
     *     returns org.rtcproject.mnp_ws.RTCACCOUNTCREATERESPONSE
     * @throws PORTINFault1
     */
    @WebMethod(operationName = "PORTIN")
    @WebResult(name = "RTC_PORTIN_RES", targetNamespace = "http://rtcproject.org/MNP_WS", partName = "RTC_PORTIN_RES")
    public RTCACCOUNTCREATERESPONSE portin(
        @WebParam(name = "RTC_PORTIN", targetNamespace = "http://rtcproject.org/MNP_WS", partName = "RTC_PORTIN")
        RTCPORTINWS rtcPORTIN)
        throws PORTINFault1
    ;

    /**
     * 
     * @param rtcPORTQUERY
     * @return
     *     returns org.rtcproject.mnp_ws.RTCQUERYRES
     */
    @WebMethod(operationName = "PORTQUERY")
    @WebResult(name = "RTC_PORT_RES", targetNamespace = "http://rtcproject.org/MNP_WS", partName = "RTC_PORT_RES")
    public RTCQUERYRES portquery(
        @WebParam(name = "RTC_PORT_QUERY", targetNamespace = "http://rtcproject.org/MNP_WS", partName = "RTC_PORT_QUERY")
        RTCPORT rtcPORTQUERY);

    /**
     * 
     * @param rtcPORTOUT
     * @return
     *     returns org.rtcproject.mnp_ws.RTCTERMINATESERVICERESPONSE
     * @throws PORTOUTFault1
     */
    @WebMethod(operationName = "PORTOUT")
    @WebResult(name = "RTC_PORTOUT_RES", targetNamespace = "http://rtcproject.org/MNP_WS", partName = "RTC_PORTOUT_RES")
    public RTCTERMINATESERVICERESPONSE portout(
        @WebParam(name = "RTC_PORTOUT", targetNamespace = "http://rtcproject.org/MNP_WS", partName = "RTC_PORTOUT")
        RTCPORTOUT rtcPORTOUT)
        throws PORTOUTFault1
    ;

}
