package cat.sd.domain.api;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2561-05-12T23:30:56.869+07:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "SubscriberInfoInterfaceService", 
                  wsdlLocation = "classpath:wsdl/smd.wsdl",
                  targetNamespace = "http://domain.sd.cat/") 
public class SubscriberInfoInterfaceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://domain.sd.cat/", "SubscriberInfoInterfaceService");
    public final static QName SubscriberInfoInterfacePort = new QName("http://domain.sd.cat/", "SubscriberInfoInterfacePort");
    static {
        URL url = SubscriberInfoInterfaceService.class.getClassLoader().getResource("wsdl/smd.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SubscriberInfoInterfaceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/smd.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public SubscriberInfoInterfaceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SubscriberInfoInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubscriberInfoInterfaceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SubscriberInfoInterfaceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SubscriberInfoInterfaceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SubscriberInfoInterfaceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SubscriberInfoInterface
     */
    @WebEndpoint(name = "SubscriberInfoInterfacePort")
    public SubscriberInfoInterface getSubscriberInfoInterfacePort() {
        return super.getPort(SubscriberInfoInterfacePort, SubscriberInfoInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubscriberInfoInterface
     */
    @WebEndpoint(name = "SubscriberInfoInterfacePort")
    public SubscriberInfoInterface getSubscriberInfoInterfacePort(WebServiceFeature... features) {
        return super.getPort(SubscriberInfoInterfacePort, SubscriberInfoInterface.class, features);
    }

}
