
package org.rtcproject.ws.jaxb;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RTC_DEALERIN_FALUT_RES", targetNamespace = "http://rtcproject.org/DL_WS")
public class RTCDEALERINFault1
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RTCWSFAULT faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public RTCDEALERINFault1(String message, RTCWSFAULT faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public RTCDEALERINFault1(String message, RTCWSFAULT faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.rtcproject.dl_ws.RTCWSFAULT
     */
    public RTCWSFAULT getFaultInfo() {
        return faultInfo;
    }

}
