
package com.netnumber.titan.view.soap.api;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-11-24T14:12:15.441+07:00
 * Generated source version: 3.2.1
 * 
 */
public final class ViewSOAPProvisioning_ViewSOAPProvisioning_Client {

    private static final QName SERVICE_NAME = new QName("http://www.netnumber.com/titan/view/soap/api", "ViewSOAPProvisioning");

    private ViewSOAPProvisioning_ViewSOAPProvisioning_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ViewSOAPProvisioning_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ViewSOAPProvisioning_Service ss = new ViewSOAPProvisioning_Service(wsdlURL, SERVICE_NAME);
        ViewSOAPProvisioning port = ss.getViewSOAPProvisioning();  
        
        {
        System.out.println("Invoking change...");
        com.netnumber.titan.view.soap.types.ChangeRequest _change_changeRequest = null;
        com.netnumber.titan.view.soap.types.ChangeResponse _change__return = port.change(_change_changeRequest);
        System.out.println("change.result=" + _change__return);


        }
        {
        System.out.println("Invoking get...");
        com.netnumber.titan.view.soap.types.GetRequest _get_getRequest = null;
        com.netnumber.titan.view.soap.types.GetResponse _get__return = port.get(_get_getRequest);
        System.out.println("get.result=" + _get__return);


        }
        {
        System.out.println("Invoking status...");
        java.lang.Object _status_statusRequest = new java.lang.Object();
        com.netnumber.titan.view.soap.types.StatusResponse _status__return = port.status(_status_statusRequest);
        System.out.println("status.result=" + _status__return);


        }

        System.exit(0);
    }

}
