package com.netnumber.titan.view.soap.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-11-24T14:12:15.493+07:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "ViewSOAPProvisioning", 
                  wsdlLocation = "file:view-soap-api.wsdl",
                  targetNamespace = "http://www.netnumber.com/titan/view/soap/api") 
public class ViewSOAPProvisioning_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.netnumber.com/titan/view/soap/api", "ViewSOAPProvisioning");
    public final static QName ViewSOAPProvisioning = new QName("http://www.netnumber.com/titan/view/soap/api", "ViewSOAPProvisioning");
    static {
        URL url = null;
        try {
            url = new URL("file:view-soap-api.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ViewSOAPProvisioning_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:view-soap-api.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ViewSOAPProvisioning_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ViewSOAPProvisioning_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ViewSOAPProvisioning_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ViewSOAPProvisioning_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ViewSOAPProvisioning_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ViewSOAPProvisioning_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ViewSOAPProvisioning
     */
    @WebEndpoint(name = "ViewSOAPProvisioning")
    public ViewSOAPProvisioning getViewSOAPProvisioning() {
        return super.getPort(ViewSOAPProvisioning, ViewSOAPProvisioning.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ViewSOAPProvisioning
     */
    @WebEndpoint(name = "ViewSOAPProvisioning")
    public ViewSOAPProvisioning getViewSOAPProvisioning(WebServiceFeature... features) {
        return super.getPort(ViewSOAPProvisioning, ViewSOAPProvisioning.class, features);
    }

}
