//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.25 at 11:08:32 PM ICT 
//


package com.eviware.soapui.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://eviware.com/soapui/config}settings"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}threadCount"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}startDelay"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}sampleInterval"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}calculateTPSOnTimePassed"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}resetStatisticsOnThreadCountChange"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}historyLimit"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}testLimit"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}limitType"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}loadStrategy"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}assertion"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}maxAssertionErrors"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}cancelExcessiveThreads"/>
 *         &lt;element ref="{http://eviware.com/soapui/config}strategyInterval"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "settings",
    "threadCount",
    "startDelay",
    "sampleInterval",
    "calculateTPSOnTimePassed",
    "resetStatisticsOnThreadCountChange",
    "historyLimit",
    "testLimit",
    "limitType",
    "loadStrategy",
    "assertion",
    "maxAssertionErrors",
    "cancelExcessiveThreads",
    "strategyInterval"
})
@XmlRootElement(name = "loadTest")
public class LoadTest {

    @XmlElement(required = true)
    protected Settings settings;
    protected byte threadCount;
    protected byte startDelay;
    protected short sampleInterval;
    @XmlElement(required = true)
    protected String calculateTPSOnTimePassed;
    @XmlElement(required = true)
    protected String resetStatisticsOnThreadCountChange;
    protected byte historyLimit;
    protected byte testLimit;
    @XmlElement(required = true)
    protected String limitType;
    @XmlElement(required = true)
    protected LoadStrategy loadStrategy;
    @XmlElement(required = true)
    protected Assertion assertion;
    protected byte maxAssertionErrors;
    @XmlElement(required = true)
    protected String cancelExcessiveThreads;
    protected short strategyInterval;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the settings property.
     * 
     * @return
     *     possible object is
     *     {@link Settings }
     *     
     */
    public Settings getSettings() {
        return settings;
    }

    /**
     * Sets the value of the settings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Settings }
     *     
     */
    public void setSettings(Settings value) {
        this.settings = value;
    }

    /**
     * Gets the value of the threadCount property.
     * 
     */
    public byte getThreadCount() {
        return threadCount;
    }

    /**
     * Sets the value of the threadCount property.
     * 
     */
    public void setThreadCount(byte value) {
        this.threadCount = value;
    }

    /**
     * Gets the value of the startDelay property.
     * 
     */
    public byte getStartDelay() {
        return startDelay;
    }

    /**
     * Sets the value of the startDelay property.
     * 
     */
    public void setStartDelay(byte value) {
        this.startDelay = value;
    }

    /**
     * Gets the value of the sampleInterval property.
     * 
     */
    public short getSampleInterval() {
        return sampleInterval;
    }

    /**
     * Sets the value of the sampleInterval property.
     * 
     */
    public void setSampleInterval(short value) {
        this.sampleInterval = value;
    }

    /**
     * Gets the value of the calculateTPSOnTimePassed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalculateTPSOnTimePassed() {
        return calculateTPSOnTimePassed;
    }

    /**
     * Sets the value of the calculateTPSOnTimePassed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalculateTPSOnTimePassed(String value) {
        this.calculateTPSOnTimePassed = value;
    }

    /**
     * Gets the value of the resetStatisticsOnThreadCountChange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResetStatisticsOnThreadCountChange() {
        return resetStatisticsOnThreadCountChange;
    }

    /**
     * Sets the value of the resetStatisticsOnThreadCountChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResetStatisticsOnThreadCountChange(String value) {
        this.resetStatisticsOnThreadCountChange = value;
    }

    /**
     * Gets the value of the historyLimit property.
     * 
     */
    public byte getHistoryLimit() {
        return historyLimit;
    }

    /**
     * Sets the value of the historyLimit property.
     * 
     */
    public void setHistoryLimit(byte value) {
        this.historyLimit = value;
    }

    /**
     * Gets the value of the testLimit property.
     * 
     */
    public byte getTestLimit() {
        return testLimit;
    }

    /**
     * Sets the value of the testLimit property.
     * 
     */
    public void setTestLimit(byte value) {
        this.testLimit = value;
    }

    /**
     * Gets the value of the limitType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLimitType() {
        return limitType;
    }

    /**
     * Sets the value of the limitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLimitType(String value) {
        this.limitType = value;
    }

    /**
     * Gets the value of the loadStrategy property.
     * 
     * @return
     *     possible object is
     *     {@link LoadStrategy }
     *     
     */
    public LoadStrategy getLoadStrategy() {
        return loadStrategy;
    }

    /**
     * Sets the value of the loadStrategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadStrategy }
     *     
     */
    public void setLoadStrategy(LoadStrategy value) {
        this.loadStrategy = value;
    }

    /**
     * Gets the value of the assertion property.
     * 
     * @return
     *     possible object is
     *     {@link Assertion }
     *     
     */
    public Assertion getAssertion() {
        return assertion;
    }

    /**
     * Sets the value of the assertion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Assertion }
     *     
     */
    public void setAssertion(Assertion value) {
        this.assertion = value;
    }

    /**
     * Gets the value of the maxAssertionErrors property.
     * 
     */
    public byte getMaxAssertionErrors() {
        return maxAssertionErrors;
    }

    /**
     * Sets the value of the maxAssertionErrors property.
     * 
     */
    public void setMaxAssertionErrors(byte value) {
        this.maxAssertionErrors = value;
    }

    /**
     * Gets the value of the cancelExcessiveThreads property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelExcessiveThreads() {
        return cancelExcessiveThreads;
    }

    /**
     * Sets the value of the cancelExcessiveThreads property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelExcessiveThreads(String value) {
        this.cancelExcessiveThreads = value;
    }

    /**
     * Gets the value of the strategyInterval property.
     * 
     */
    public short getStrategyInterval() {
        return strategyInterval;
    }

    /**
     * Sets the value of the strategyInterval property.
     * 
     */
    public void setStrategyInterval(short value) {
        this.strategyInterval = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
