package com.sicap.ussdgw;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-18T10:20:51.389+07:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://SICAP_SERVER/WSDL", name = "soap_gatewayPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(use = SOAPBinding.Use.ENCODED, parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SoapGatewayPortType {

    @WebMethod
    @WebResult(name = "processUMBReqArrResponse")
    public ProcessUMBReqOutput processUMBReqArr(ProcessUMBReqInput processUMBReqInput
    );
}
