//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 11:06:53 PM ICT 
//


package com.telcordia.inpac.ws.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NPCDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NPCDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageHeader" type="{}MessageHeaderType"/>
 *         &lt;element name="NPCMessages" type="{}NPCMessageType"/>
 *         &lt;element name="MessageFooter" type="{}MessageFooterType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NPCDataType", propOrder = {
    "messageHeader",
    "npcMessages",
    "messageFooter"
})
public class NPCDataType {

    @XmlElement(name = "MessageHeader", required = true)
    protected MessageHeaderType messageHeader;
    @XmlElement(name = "NPCMessages", required = true)
    protected NPCMessageType npcMessages;
    @XmlElement(name = "MessageFooter", required = true)
    protected MessageFooterType messageFooter;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MessageHeaderType }
     *     
     */
    public MessageHeaderType getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageHeaderType }
     *     
     */
    public void setMessageHeader(MessageHeaderType value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the npcMessages property.
     * 
     * @return
     *     possible object is
     *     {@link NPCMessageType }
     *     
     */
    public NPCMessageType getNPCMessages() {
        return npcMessages;
    }

    /**
     * Sets the value of the npcMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link NPCMessageType }
     *     
     */
    public void setNPCMessages(NPCMessageType value) {
        this.npcMessages = value;
    }

    /**
     * Gets the value of the messageFooter property.
     * 
     * @return
     *     possible object is
     *     {@link MessageFooterType }
     *     
     */
    public MessageFooterType getMessageFooter() {
        return messageFooter;
    }

    /**
     * Sets the value of the messageFooter property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageFooterType }
     *     
     */
    public void setMessageFooter(MessageFooterType value) {
        this.messageFooter = value;
    }

}
