//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 11:06:53 PM ICT 
//


package com.telcordia.inpac.ws.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NumReturnReqMsgType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NumReturnReqMsgType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrderId" type="{}OrderIdType"/>
 *         &lt;element name="NumberNoPortId" type="{}NumTypeNoPortId" maxOccurs="6000"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NumReturnReqMsgType", propOrder = {
    "orderId",
    "numberNoPortId"
})
public class NumReturnReqMsgType {

    @XmlElement(name = "OrderId", required = true)
    protected String orderId;
    @XmlElement(name = "NumberNoPortId", required = true)
    protected List<NumTypeNoPortId> numberNoPortId;

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the numberNoPortId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the numberNoPortId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
    getNumberNoPortId().add(newItem);
 </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NumTypeNoPortId }
     * 
     * 
     */
    public List<NumTypeNoPortId> getNumberNoPortId() {
        if (numberNoPortId == null) {
            numberNoPortId = new ArrayList<NumTypeNoPortId>();
        }
        return this.numberNoPortId;
    }

    public void setNumberNoPortId(List<NumTypeNoPortId> numberNoPortId) {
        this.numberNoPortId = numberNoPortId;
    }
    
}
