//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.26 at 11:06:53 PM ICT 
//


package com.telcordia.inpac.ws.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NPCMessageData }
     * 
     */
    public NPCMessageData createNPCMessageData() {
        return new NPCMessageData();
    }

    /**
     * Create an instance of {@link NPCDataType }
     * 
     */
    public NPCDataType createNPCDataType() {
        return new NPCDataType();
    }

    /**
     * Create an instance of {@link PortDeactMsgType }
     * 
     */
    public PortDeactMsgType createPortDeactMsgType() {
        return new PortDeactMsgType();
    }

    /**
     * Create an instance of {@link NumReturnReqMsgType }
     * 
     */
    public NumReturnReqMsgType createNumReturnReqMsgType() {
        return new NumReturnReqMsgType();
    }

    /**
     * Create an instance of {@link NPCMessageType }
     * 
     */
    public NPCMessageType createNPCMessageType() {
        return new NPCMessageType();
    }

    /**
     * Create an instance of {@link NumTypeWithPinWithCLHFlag }
     * 
     */
    public NumTypeWithPinWithCLHFlag createNumTypeWithPinWithCLHFlag() {
        return new NumTypeWithPinWithCLHFlag();
    }

    /**
     * Create an instance of {@link NumTypeWithPin }
     * 
     */
    public NumTypeWithPin createNumTypeWithPin() {
        return new NumTypeWithPin();
    }

    /**
     * Create an instance of {@link NumTypeWithFlagWithPortDate }
     * 
     */
    public NumTypeWithFlagWithPortDate createNumTypeWithFlagWithPortDate() {
        return new NumTypeWithFlagWithPortDate();
    }

    /**
     * Create an instance of {@link MessageFooterType }
     * 
     */
    public MessageFooterType createMessageFooterType() {
        return new MessageFooterType();
    }

    /**
     * Create an instance of {@link SyncReqMsgType }
     * 
     */
    public SyncReqMsgType createSyncReqMsgType() {
        return new SyncReqMsgType();
    }

    /**
     * Create an instance of {@link PortTerminatedMsgType }
     * 
     */
    public PortTerminatedMsgType createPortTerminatedMsgType() {
        return new PortTerminatedMsgType();
    }

    /**
     * Create an instance of {@link ErrorNotifMsgType }
     * 
     */
    public ErrorNotifMsgType createErrorNotifMsgType() {
        return new ErrorNotifMsgType();
    }

    /**
     * Create an instance of {@link NumTypeNoPortId }
     * 
     */
    public NumTypeNoPortId createNumTypeNoPortId() {
        return new NumTypeNoPortId();
    }

    /**
     * Create an instance of {@link PortReqAckMsgType }
     * 
     */
    public PortReqAckMsgType createPortReqAckMsgType() {
        return new PortReqAckMsgType();
    }

    /**
     * Create an instance of {@link PortReqMsgType }
     * 
     */
    public PortReqMsgType createPortReqMsgType() {
        return new PortReqMsgType();
    }

    /**
     * Create an instance of {@link PortNotMsgType }
     * 
     */
    public PortNotMsgType createPortNotMsgType() {
        return new PortNotMsgType();
    }

    /**
     * Create an instance of {@link MessageHeaderType }
     * 
     */
    public MessageHeaderType createMessageHeaderType() {
        return new MessageHeaderType();
    }

    /**
     * Create an instance of {@link TimerNotifMsgType }
     * 
     */
    public TimerNotifMsgType createTimerNotifMsgType() {
        return new TimerNotifMsgType();
    }

    /**
     * Create an instance of {@link NumTypeWithPinNoPortId }
     * 
     */
    public NumTypeWithPinNoPortId createNumTypeWithPinNoPortId() {
        return new NumTypeWithPinNoPortId();
    }

    /**
     * Create an instance of {@link NumTypeBase }
     * 
     */
    public NumTypeBase createNumTypeBase() {
        return new NumTypeBase();
    }

    /**
     * Create an instance of {@link PortBroadcastMsgType }
     * 
     */
    public PortBroadcastMsgType createPortBroadcastMsgType() {
        return new PortBroadcastMsgType();
    }

    /**
     * Create an instance of {@link NumReturnFwdMsgType }
     * 
     */
    public NumReturnFwdMsgType createNumReturnFwdMsgType() {
        return new NumReturnFwdMsgType();
    }

    /**
     * Create an instance of {@link SubscriberDataType }
     * 
     */
    public SubscriberDataType createSubscriberDataType() {
        return new SubscriberDataType();
    }

    /**
     * Create an instance of {@link PortRvrsRecipientMsgType }
     * 
     */
    public PortRvrsRecipientMsgType createPortRvrsRecipientMsgType() {
        return new PortRvrsRecipientMsgType();
    }

    /**
     * Create an instance of {@link NumReturnAckMsgType }
     * 
     */
    public NumReturnAckMsgType createNumReturnAckMsgType() {
        return new NumReturnAckMsgType();
    }

    /**
     * Create an instance of {@link PortRespMsgType }
     * 
     */
    public PortRespMsgType createPortRespMsgType() {
        return new PortRespMsgType();
    }

    /**
     * Create an instance of {@link NumTypeWithCLHFlag }
     * 
     */
    public NumTypeWithCLHFlag createNumTypeWithCLHFlag() {
        return new NumTypeWithCLHFlag();
    }

    /**
     * Create an instance of {@link PortReqFwdMsgType }
     * 
     */
    public PortReqFwdMsgType createPortReqFwdMsgType() {
        return new PortReqFwdMsgType();
    }

    /**
     * Create an instance of {@link PortNotExceptMsgType }
     * 
     */
    public PortNotExceptMsgType createPortNotExceptMsgType() {
        return new PortNotExceptMsgType();
    }

    /**
     * Create an instance of {@link PortRvrsDonorMsgType }
     * 
     */
    public PortRvrsDonorMsgType createPortRvrsDonorMsgType() {
        return new PortRvrsDonorMsgType();
    }

    /**
     * Create an instance of {@link SyncRespMsgType }
     * 
     */
    public SyncRespMsgType createSyncRespMsgType() {
        return new SyncRespMsgType();
    }

    /**
     * Create an instance of {@link NumTypeWithFlag }
     * 
     */
    public NumTypeWithFlag createNumTypeWithFlag() {
        return new NumTypeWithFlag();
    }

    /**
     * Create an instance of {@link PortCancelMsgType }
     * 
     */
    public PortCancelMsgType createPortCancelMsgType() {
        return new PortCancelMsgType();
    }

}
